version: '3.5'
services:
  irene-voice-assistant-docker:
    image: firefly27/irene-voice-assistant-docker
    container_name: irene-voice-assistant-docker
    devices:
      - /dev/snd:/dev/snd
    volumes: 
      - ./requirements-docker.txt:/home/python/irene/requirements-docker.txt   #requirements для установки внутри контейнера
      - ./irene_options:/home/python/irene/options                      #основные настройки
      - ./docker_plugins:/home/python/irene/plugins                     #папка для плагинов
      - ./runva_webapi_docker.json:/home/python/irene/runva_webapi.json #настройка webapi
    ports:
      - 5003:5003
      - 5004:5004
    tty: true
    logging:
      driver: syslog
      options:
        mode: non-blocking
    restart: unless-stopped
# не забудьте скачать нужные файлы и плагины для контейнера https://github.com/Ivan-Firefly/Irene-Voice-Assistant-Docker/blob/master/download.sh
