version: '3.5'
services:
  irene-va-docker:
    image: firefly27/irene-va-docker
    container_name: irene-va-docker
    devices:
      - /dev/snd:/dev/snd
    volumes: 
      - ./requirements-docker.txt:/home/python/irene/requirements.txt   #requirements для установки внутри контейнера
      - ./irene_options:/home/python/irene/options                      #основные настройки
      - ./docker_plugins:/home/python/irene/plugins                     #папка для плагинов
      - ./runva_webapi_docker.json:/home/python/irene/runva_webapi.json #настройка webapi
    ports:
      - 5003:5003
      - 5004:5004
    restart: unless-stopped
