version: '3.5'
services:
  irene-va-docker:
    image: firefly27/irene-va-docker
    container_name: irene-va-docker
    devices:
      - /dev/snd:/dev/snd
    volumes: 
      - ./irene_options:/home/python/irene/options #основные настройки
      - ./docker_plugins:/home/python/irene/plugins #папка для плагинов
      - ./runva_webapi_docker.json:/home/python/irene/runva_webapi.json #настройки web сервера     
    ports:
      - 5003:5003
    restart: unless-stopped
