version: '3.5'
services:
  irene-voice-assistant-docker:
    image: firefly27/irene-voice-assistant-docker
    container_name: irene-voice-assistant-docker
    devices:
      - /dev/snd:/dev/snd
    volumes: 
      - ./requirements-docker.txt:/home/python/irene/requirements.txt   #requirements для установки внутри контейнера
      - ./irene_options:/home/python/irene/options                      #основные настройки
      - ./docker_plugins:/home/python/irene/plugins                     #папка для плагинов
      - ./runva_webapi_docker.json:/home/python/irene/runva_webapi.json #настройка webapi
    ports:
      - 5003:5003
      - 5004:5004
    tty: true
    logging:
      driver: syslog
      options:
        mode: non-blocking
    restart: unless-stopped
    # command: sh -c "pip install --no-cache-dir -r requirements.txt && python3 runva_webapi.py & python3 vosk_asr_server.py"
