version: '3.5'
services:
  va:
    image: Irene-VA-Docker
    container_name: Irene-VA-Docker
    devices:
      - /dev/snd:/dev/snd
    volumes: 
      - /va/irene_options:/home/python/irene/options #основные настройки
      - /va/runva_webapi.json:/home/python/irene/runva_webapi.json #настройки web сервера
      - /va/plugins:/home/python/irene/plugins #папка для плагинов
    ports:
      - 5003:5003
    restart: unless-stopped
